//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IEktronFormService")]
public interface IEktronFormService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEktronFormService/submitFormData", ReplyAction = "http://tempuri.org/IEktronFormService/submitFormDataResponse")]
    void submitFormData(Ektron.Cms.FormData formData, Ektron.Cms.FormSubmittedData formSubmittedData, string[] strKeyValues);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEktronFormServiceChannel : IEktronFormService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EktronFormServiceClient : System.ServiceModel.ClientBase<IEktronFormService>, IEktronFormService
{

    public EktronFormServiceClient()
    {
    }

    public EktronFormServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public EktronFormServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public EktronFormServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public EktronFormServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public void submitFormData(Ektron.Cms.FormData formData, Ektron.Cms.FormSubmittedData formSubmittedData, string[] strKeyValues)
    {
        base.Channel.submitFormData(formData, formSubmittedData, strKeyValues);
    }
}