//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dev.virtualearth.net/webservices/v1/common", ClrNamespace="dev.virtualearth.net.webservices.v1.common")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dev.virtualearth.net/webservices/v1/route", ClrNamespace="dev.virtualearth.net.webservices.v1.route")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dev.virtualearth.net/webservices/v1/geocode", ClrNamespace = "dev.virtualearth.net.webservices.v1.geocode")]

namespace dev.virtualearth.net.webservices.v1.common
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RequestBase", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.route.MajorRoutesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.route.RouteRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private dev.virtualearth.net.webservices.v1.common.Credentials CredentialsField;

        private string CultureField;

        private dev.virtualearth.net.webservices.v1.common.ExecutionOptions ExecutionOptionsField;

        private dev.virtualearth.net.webservices.v1.common.UserProfile UserProfileField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Credentials Credentials
        {
            get
            {
                return this.CredentialsField;
            }
            set
            {
                this.CredentialsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ExecutionOptions ExecutionOptions
        {
            get
            {
                return this.ExecutionOptionsField;
            }
            set
            {
                this.ExecutionOptionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.UserProfile UserProfile
        {
            get
            {
                return this.UserProfileField;
            }
            set
            {
                this.UserProfileField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Credentials", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ApplicationIdField;

        private string TokenField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExecutionOptions", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuppressFaultsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuppressFaults
        {
            get
            {
                return this.SuppressFaultsField;
            }
            set
            {
                this.SuppressFaultsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserProfile", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private dev.virtualearth.net.webservices.v1.common.Heading CurrentHeadingField;

        private dev.virtualearth.net.webservices.v1.common.UserLocation CurrentLocationField;

        private dev.virtualearth.net.webservices.v1.common.DeviceType DeviceTypeField;

        private dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnitField;

        private string IPAddressField;

        private dev.virtualearth.net.webservices.v1.common.ShapeBase MapViewField;

        private dev.virtualearth.net.webservices.v1.common.SizeOfint ScreenSizeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Heading CurrentHeading
        {
            get
            {
                return this.CurrentHeadingField;
            }
            set
            {
                this.CurrentHeadingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.UserLocation CurrentLocation
        {
            get
            {
                return this.CurrentLocationField;
            }
            set
            {
                this.CurrentLocationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.DeviceType DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnit
        {
            get
            {
                return this.DistanceUnitField;
            }
            set
            {
                this.DistanceUnitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ShapeBase MapView
        {
            get
            {
                return this.MapViewField;
            }
            set
            {
                this.MapViewField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.SizeOfint ScreenSize
        {
            get
            {
                return this.ScreenSizeField;
            }
            set
            {
                this.ScreenSizeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Address", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AddressLineField;

        private string AdminDistrictField;

        private string CountryRegionField;

        private string DistrictField;

        private string FormattedAddressField;

        private string LocalityField;

        private string PostalCodeField;

        private string PostalTownField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine
        {
            get
            {
                return this.AddressLineField;
            }
            set
            {
                this.AddressLineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminDistrict
        {
            get
            {
                return this.AdminDistrictField;
            }
            set
            {
                this.AdminDistrictField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegion
        {
            get
            {
                return this.CountryRegionField;
            }
            set
            {
                this.CountryRegionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormattedAddress
        {
            get
            {
                return this.FormattedAddressField;
            }
            set
            {
                this.FormattedAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locality
        {
            get
            {
                return this.LocalityField;
            }
            set
            {
                this.LocalityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalTown
        {
            get
            {
                return this.PostalTownField;
            }
            set
            {
                this.PostalTownField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Heading", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private double OrientationField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Orientation
        {
            get
            {
                return this.OrientationField;
            }
            set
            {
                this.OrientationField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserLocation", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : dev.virtualearth.net.webservices.v1.common.Location
    {

        private dev.virtualearth.net.webservices.v1.common.Confidence ConfidenceField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Confidence Confidence
        {
            get
            {
                return this.ConfidenceField;
            }
            set
            {
                this.ConfidenceField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ShapeBase", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.Rectangle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.Circle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.Polygon))]
    public partial class ShapeBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SizeOfint", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int HeightField;

        private int WidthField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DeviceType", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desktop = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 1,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DistanceUnit", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kilometer = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mile = 1,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Location", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.GeocodeLocation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.UserLocation))]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private double AltitudeField;

        private double LatitudeField;

        private double LongitudeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altitude
        {
            get
            {
                return this.AltitudeField;
            }
            set
            {
                this.AltitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GeocodeLocation", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : dev.virtualearth.net.webservices.v1.common.Location
    {

        private string CalculationMethodField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalculationMethod
        {
            get
            {
                return this.CalculationMethodField;
            }
            set
            {
                this.CalculationMethodField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Confidence", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Rectangle", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {

        private dev.virtualearth.net.webservices.v1.common.Location NortheastField;

        private dev.virtualearth.net.webservices.v1.common.Location SouthwestField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Northeast
        {
            get
            {
                return this.NortheastField;
            }
            set
            {
                this.NortheastField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Southwest
        {
            get
            {
                return this.SouthwestField;
            }
            set
            {
                this.SouthwestField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Circle", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {

        private dev.virtualearth.net.webservices.v1.common.Location CenterField;

        private dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnitField;

        private double RadiusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Center
        {
            get
            {
                return this.CenterField;
            }
            set
            {
                this.CenterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnit
        {
            get
            {
                return this.DistanceUnitField;
            }
            set
            {
                this.DistanceUnitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Radius
        {
            get
            {
                return this.RadiusField;
            }
            set
            {
                this.RadiusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Polygon", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {

        private dev.virtualearth.net.webservices.v1.common.Location[] VerticesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location[] Vertices
        {
            get
            {
                return this.VerticesField;
            }
            set
            {
                this.VerticesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseBase", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.route.MajorRoutesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.route.RouteResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Uri BrandLogoUriField;

        private dev.virtualearth.net.webservices.v1.common.ResponseSummary ResponseSummaryField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri BrandLogoUri
        {
            get
            {
                return this.BrandLogoUriField;
            }
            set
            {
                this.BrandLogoUriField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ResponseSummary ResponseSummary
        {
            get
            {
                return this.ResponseSummaryField;
            }
            set
            {
                this.ResponseSummaryField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseSummary", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private dev.virtualearth.net.webservices.v1.common.AuthenticationResultCode AuthenticationResultCodeField;

        private string CopyrightField;

        private string FaultReasonField;

        private dev.virtualearth.net.webservices.v1.common.ResponseStatusCode StatusCodeField;

        private string TraceIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.AuthenticationResultCode AuthenticationResultCode
        {
            get
            {
                return this.AuthenticationResultCodeField;
            }
            set
            {
                this.AuthenticationResultCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Copyright
        {
            get
            {
                return this.CopyrightField;
            }
            set
            {
                this.CopyrightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultReason
        {
            get
            {
                return this.FaultReasonField;
            }
            set
            {
                this.FaultReasonField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ResponseStatusCode StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraceId
        {
            get
            {
                return this.TraceIdField;
            }
            set
            {
                this.TraceIdField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AuthenticationResultCode", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCredentials = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidCredentials = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCredentials = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CredentialsExpired = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthorized = 7,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseStatusCode", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerError = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GeocodeResult", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private dev.virtualearth.net.webservices.v1.common.Address AddressField;

        private dev.virtualearth.net.webservices.v1.common.Rectangle BestViewField;

        private dev.virtualearth.net.webservices.v1.common.Confidence ConfidenceField;

        private string DisplayNameField;

        private string EntityTypeField;

        private dev.virtualearth.net.webservices.v1.common.GeocodeLocation[] LocationsField;

        private string[] MatchCodesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Rectangle BestView
        {
            get
            {
                return this.BestViewField;
            }
            set
            {
                this.BestViewField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Confidence Confidence
        {
            get
            {
                return this.ConfidenceField;
            }
            set
            {
                this.ConfidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityType
        {
            get
            {
                return this.EntityTypeField;
            }
            set
            {
                this.EntityTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.GeocodeLocation[] Locations
        {
            get
            {
                return this.LocationsField;
            }
            set
            {
                this.LocationsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MatchCodes
        {
            get
            {
                return this.MatchCodesField;
            }
            set
            {
                this.MatchCodesField = value;
            }
        }
    }
}

namespace dev.virtualearth.net.webservices.v1.route
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MajorRoutesRequest", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesRequest : dev.virtualearth.net.webservices.v1.common.RequestBase
    {
        
        private dev.virtualearth.net.webservices.v1.route.Waypoint DestinationField;
        
        private dev.virtualearth.net.webservices.v1.route.MajorRoutesOptions OptionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.Waypoint Destination
        {
            get
            {
                return this.DestinationField;
            }
            set
            {
                this.DestinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.MajorRoutesOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteRequest", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteRequest : dev.virtualearth.net.webservices.v1.common.RequestBase
    {
        
        private dev.virtualearth.net.webservices.v1.route.RouteOptions OptionsField;
        
        private dev.virtualearth.net.webservices.v1.route.Waypoint[] WaypointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.Waypoint[] Waypoints
        {
            get
            {
                return this.WaypointsField;
            }
            set
            {
                this.WaypointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteOptions", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.route.MajorRoutesOptions))]
    public partial class RouteOptions : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.route.TravelMode ModeField;
        
        private dev.virtualearth.net.webservices.v1.route.RouteOptimization OptimizationField;
        
        private dev.virtualearth.net.webservices.v1.route.RoutePathType RoutePathTypeField;
        
        private dev.virtualearth.net.webservices.v1.route.TrafficUsage TrafficUsageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.TravelMode Mode
        {
            get
            {
                return this.ModeField;
            }
            set
            {
                this.ModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteOptimization Optimization
        {
            get
            {
                return this.OptimizationField;
            }
            set
            {
                this.OptimizationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RoutePathType RoutePathType
        {
            get
            {
                return this.RoutePathTypeField;
            }
            set
            {
                this.RoutePathTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.TrafficUsage TrafficUsage
        {
            get
            {
                return this.TrafficUsageField;
            }
            set
            {
                this.TrafficUsageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Waypoint", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class Waypoint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private dev.virtualearth.net.webservices.v1.common.Location LocationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MajorRoutesOptions", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesOptions : dev.virtualearth.net.webservices.v1.route.RouteOptions
    {
        
        private bool ReturnRoutesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnRoutes
        {
            get
            {
                return this.ReturnRoutesField;
            }
            set
            {
                this.ReturnRoutesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelMode", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum TravelMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Driving = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Walking = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteOptimization", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum RouteOptimization : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinimizeTime = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinimizeDistance = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoutePathType", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum RoutePathType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Points = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrafficUsage", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum TrafficUsage : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrafficBasedTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrafficBasedRouteAndTime = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MajorRoutesResponse", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesResponse : dev.virtualearth.net.webservices.v1.common.ResponseBase
    {
        
        private dev.virtualearth.net.webservices.v1.route.RouteResult[] RoutesField;
        
        private dev.virtualearth.net.webservices.v1.route.Waypoint[] StartingPointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteResult[] Routes
        {
            get
            {
                return this.RoutesField;
            }
            set
            {
                this.RoutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.Waypoint[] StartingPoints
        {
            get
            {
                return this.StartingPointsField;
            }
            set
            {
                this.StartingPointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteResponse", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteResponse : dev.virtualearth.net.webservices.v1.common.ResponseBase
    {
        
        private dev.virtualearth.net.webservices.v1.route.RouteResult ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteResult Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteResult", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.route.RouteLeg[] LegsField;
        
        private dev.virtualearth.net.webservices.v1.route.RoutePath RoutePathField;
        
        private dev.virtualearth.net.webservices.v1.route.RouteSummary SummaryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteLeg[] Legs
        {
            get
            {
                return this.LegsField;
            }
            set
            {
                this.LegsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RoutePath RoutePath
        {
            get
            {
                return this.RoutePathField;
            }
            set
            {
                this.RoutePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteSummary Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoutePath", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RoutePath : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.common.Location[] PointsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location[] Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteSummary", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteSummary : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.common.Rectangle BoundingRectangleField;
        
        private double DistanceField;
        
        private long TimeInSecondsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Rectangle BoundingRectangle
        {
            get
            {
                return this.BoundingRectangleField;
            }
            set
            {
                this.BoundingRectangleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeInSeconds
        {
            get
            {
                return this.TimeInSecondsField;
            }
            set
            {
                this.TimeInSecondsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteLeg", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteLeg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.common.Location ActualEndField;
        
        private dev.virtualearth.net.webservices.v1.common.Location ActualStartField;
        
        private dev.virtualearth.net.webservices.v1.route.ItineraryItem[] ItineraryField;
        
        private dev.virtualearth.net.webservices.v1.route.RouteSummary SummaryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location ActualEnd
        {
            get
            {
                return this.ActualEndField;
            }
            set
            {
                this.ActualEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location ActualStart
        {
            get
            {
                return this.ActualStartField;
            }
            set
            {
                this.ActualStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ItineraryItem[] Itinerary
        {
            get
            {
                return this.ItineraryField;
            }
            set
            {
                this.ItineraryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteSummary Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryItem", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompassDirectionField;
        
        private dev.virtualearth.net.webservices.v1.route.ItineraryItemHint[] HintsField;
        
        private dev.virtualearth.net.webservices.v1.common.Location LocationField;
        
        private dev.virtualearth.net.webservices.v1.route.ManeuverType ManeuverTypeField;
        
        private dev.virtualearth.net.webservices.v1.route.RouteSummary SummaryField;
        
        private string TextField;
        
        private dev.virtualearth.net.webservices.v1.route.ItineraryItemWarning[] WarningsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompassDirection
        {
            get
            {
                return this.CompassDirectionField;
            }
            set
            {
                this.CompassDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ItineraryItemHint[] Hints
        {
            get
            {
                return this.HintsField;
            }
            set
            {
                this.HintsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ManeuverType ManeuverType
        {
            get
            {
                return this.ManeuverTypeField;
            }
            set
            {
                this.ManeuverTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.RouteSummary Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ItineraryItemWarning[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryItemHint", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItemHint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.route.ItineraryItemHintType HintTypeField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ItineraryItemHintType HintType
        {
            get
            {
                return this.HintTypeField;
            }
            set
            {
                this.HintTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManeuverType", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ManeuverType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DepartStart = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DepartIntermediateStop = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DepartIntermediateStopReturning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArriveFinish = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArriveIntermediateStop = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnLeft = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnRight = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnBack = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTurn = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnToStayLeft = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnToStayRight = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearLeft = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearRight = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepToStayLeft = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepToStayRight = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepToStayStraight = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepLeft = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepRight = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepStraight = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Take = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TakeRampLeft = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TakeRampRight = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TakeRampStraight = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepOnrampLeft = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepOnrampRight = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepOnrampStraight = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Merge = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Continue = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoadNameChange = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterRoundabout = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExitRoundabout = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnRightThenTurnRight = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnRightThenTurnLeft = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnRightThenBearRight = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnRightThenBearLeft = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnLeftThenTurnLeft = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnLeftThenTurnRight = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnLeftThenBearLeft = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnLeftThenBearRight = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearRightThenTurnRight = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearRightThenTurnLeft = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearRightThenBearRight = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearRightThenBearLeft = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearLeftThenTurnLeft = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearLeftThenTurnRight = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearLeftThenBearRight = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearLeftThenBearLeft = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RampThenHighwayRight = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RampThenHighwayLeft = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RampToHighwayStraight = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterThenExitRoundabout = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearThenMerge = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurnThenMerge = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BearThenKeep = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transfer = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wait = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TakeTransit = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Walk = 59,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryItemWarning", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItemWarning : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dev.virtualearth.net.webservices.v1.route.ItineraryWarningSeverity SeverityField;
        
        private string TextField;
        
        private dev.virtualearth.net.webservices.v1.route.ItineraryWarningType WarningTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ItineraryWarningSeverity Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.route.ItineraryWarningType WarningType
        {
            get
            {
                return this.WarningTypeField;
            }
            set
            {
                this.WarningTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryItemHintType", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryItemHintType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreviousIntersection = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextIntersection = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Landmark = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryWarningSeverity", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryWarningSeverity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LowImpact = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minor = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moderate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Serious = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryWarningType", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryWarningType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accident = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdminDivisionChange = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlockedRoad = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CheckTimetable = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Congestion = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CountryChange = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisabledVehicle = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GateAccess = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetOffTransit = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetOnTransit = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IllegalUTurn = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MassTransit = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Miscellaneous = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoIncident = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherNews = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherTrafficIncidents = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlannedEvent = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrivateRoad = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedTurn = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoadClosures = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RoadHazard = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledConstruction = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SeasonalClosures = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tollbooth = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TollRoad = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrafficFlow = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnpavedRoad = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnscheduledConstruction = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weather = 30,
    }
}

namespace dev.virtualearth.net.webservices.v1.geocode
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReverseGeocodeRequest", Namespace = "http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class ReverseGeocodeRequest : dev.virtualearth.net.webservices.v1.common.RequestBase
    {

        private dev.virtualearth.net.webservices.v1.common.Location LocationField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GeocodeRequest", Namespace = "http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class GeocodeRequest : dev.virtualearth.net.webservices.v1.common.RequestBase
    {

        private dev.virtualearth.net.webservices.v1.common.Address AddressField;

        private dev.virtualearth.net.webservices.v1.geocode.GeocodeOptions OptionsField;

        private string QueryField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.geocode.GeocodeOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query
        {
            get
            {
                return this.QueryField;
            }
            set
            {
                this.QueryField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GeocodeOptions", Namespace = "http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class GeocodeOptions : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<int> CountField;

        private dev.virtualearth.net.webservices.v1.geocode.FilterBase[] FiltersField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.geocode.FilterBase[] Filters
        {
            get
            {
                return this.FiltersField;
            }
            set
            {
                this.FiltersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FilterBase", Namespace = "http://dev.virtualearth.net/webservices/v1/geocode")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.geocode.ConfidenceFilter))]
    public partial class FilterBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ConfidenceFilter", Namespace = "http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class ConfidenceFilter : dev.virtualearth.net.webservices.v1.geocode.FilterBase
    {

        private dev.virtualearth.net.webservices.v1.common.Confidence MinimumConfidenceField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Confidence MinimumConfidence
        {
            get
            {
                return this.MinimumConfidenceField;
            }
            set
            {
                this.MinimumConfidenceField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GeocodeResponse", Namespace = "http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class GeocodeResponse : dev.virtualearth.net.webservices.v1.common.ResponseBase
    {

        private dev.virtualearth.net.webservices.v1.common.GeocodeResult[] ResultsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.GeocodeResult[] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts", ConfigurationName = "IGeocodeService")]
public interface IGeocodeService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
        "ode", ReplyAction = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
        "odeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(dev.virtualearth.net.webservices.v1.common.ResponseSummary), Action = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
        "odeResponseSummaryFault", Name = "ResponseSummary", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    dev.virtualearth.net.webservices.v1.geocode.GeocodeResponse Geocode(dev.virtualearth.net.webservices.v1.geocode.GeocodeRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
        "rseGeocode", ReplyAction = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
        "rseGeocodeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(dev.virtualearth.net.webservices.v1.common.ResponseSummary), Action = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
        "rseGeocodeResponseSummaryFault", Name = "ResponseSummary", Namespace = "http://dev.virtualearth.net/webservices/v1/common")]
    dev.virtualearth.net.webservices.v1.geocode.GeocodeResponse ReverseGeocode(dev.virtualearth.net.webservices.v1.geocode.ReverseGeocodeRequest request);

}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGeocodeServiceChannel : IGeocodeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GeocodeServiceClient : System.ServiceModel.ClientBase<IGeocodeService>, IGeocodeService
{

    public GeocodeServiceClient()
    {
    }

    public GeocodeServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public GeocodeServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public GeocodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public GeocodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public dev.virtualearth.net.webservices.v1.geocode.GeocodeResponse Geocode(dev.virtualearth.net.webservices.v1.geocode.GeocodeRequest request)
    {
        return base.Channel.Geocode(request);
    }

    public dev.virtualearth.net.webservices.v1.geocode.GeocodeResponse ReverseGeocode(dev.virtualearth.net.webservices.v1.geocode.ReverseGeocodeRequest request)
    {
        return base.Channel.ReverseGeocode(request);
    }

}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ConfigurationName="IRouteService")]
public interface IRouteService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
        "eRoute", ReplyAction="http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
        "eRouteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(dev.virtualearth.net.webservices.v1.common.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
        "eRouteResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    dev.virtualearth.net.webservices.v1.route.RouteResponse CalculateRoute(dev.virtualearth.net.webservices.v1.route.RouteRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
        "eRoutesFromMajorRoads", ReplyAction="http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
        "eRoutesFromMajorRoadsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(dev.virtualearth.net.webservices.v1.common.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
        "eRoutesFromMajorRoadsResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    dev.virtualearth.net.webservices.v1.route.MajorRoutesResponse CalculateRoutesFromMajorRoads(dev.virtualearth.net.webservices.v1.route.MajorRoutesRequest request);
    
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRouteServiceChannel : IRouteService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RouteServiceClient : System.ServiceModel.ClientBase<IRouteService>, IRouteService
{
    
    public RouteServiceClient()
    {
    }
    
    public RouteServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RouteServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RouteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RouteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public dev.virtualearth.net.webservices.v1.route.RouteResponse CalculateRoute(dev.virtualearth.net.webservices.v1.route.RouteRequest request)
    {
        return base.Channel.CalculateRoute(request);
    }
    
    public dev.virtualearth.net.webservices.v1.route.MajorRoutesResponse CalculateRoutesFromMajorRoads(dev.virtualearth.net.webservices.v1.route.MajorRoutesRequest request)
    {
        return base.Channel.CalculateRoutesFromMajorRoads(request);
    }
}
